apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-cloudflare
  - grafana
  - kubernetes-dashboard
  - labello
  - loki
  - netbox
  - octoprint
  - ping-exporter
  - prometheus
  - rook-cluster
  - snmp-exporter
  - snapcast-server
  - mopidy
  - heimdall
  - jellyfin
  - copyparty
  - ersatztv
