apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- autoderf2
- cert-manager-cloudflare
- grafana
- kubernetes-dashboard
- labello
- loki
- octoprint
- ping-exporter
- prometheus
- rook-cluster
- snmp-exporter
- heimdall
- jellyfin
- copyparty
- ersatztv
- zigbee
- ariang
- restreamer
- stream-recorder
